system {
    host-name CoreSwitch-JNPR;
    services {
        ssh {
            protocol-version v2;
        }
        telnet;
    }
    ntp {
        server 10.0.0.1;
    }
    syslog {
        host 10.0.0.5 any notice;
    }
}
