set deviceconfig system hostname EdgeFW-PA
set deviceconfig system ssh protocol-version v2
set deviceconfig system service disable-telnet no
set shared authentication-profile LOCAL-AUTH
set deviceconfig system ntp-servers primary-ntp-server ntp-server-address 10.0.0.1
